# Generated by Django 4.1.5 on 2023-01-21 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('publicacao', models.DateTimeField()),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2023, 1, 21, 9, 40, 18, 211434))),
            ],
        ),
    ]
