# Generated by Django 4.1.5 on 2023-01-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='arquivo',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
