# Generated by Django 4.1.5 on 2023-01-21 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_capa_alter_livro_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 11, 58, 45, 442531)),
        ),
    ]
