# Generated by Django 4.1.5 on 2023-01-21 16:08

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 13, 8, 47, 177217)),
        ),
    ]
