# Generated by Django 4.1.5 on 2023-01-22 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 21, 12, 25, 170065)),
        ),
    ]
