# Generated by Django 4.1.5 on 2023-01-25 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='publicacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='previa',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
