# Generated by Django 4.1.5 on 2023-01-25 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0014_remove_livro_conteudo_remove_livro_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='previa',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
