# Generated by Django 4.1.5 on 2023-01-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0015_alter_livro_capa_alter_livro_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
