# Generated by Django 4.1.5 on 2023-01-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0016_livro_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='arquivo',
            field=models.FileField(upload_to='images/'),
        ),
    ]
