# Generated by Django 4.1.5 on 2023-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0017_alter_livro_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='arquivo',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.FileField(upload_to='capa/'),
        ),
    ]
