# Generated by Django 4.1.5 on 2023-01-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=250)),
                ('nascimento', models.DateTimeField()),
                ('senha', models.CharField(max_length=64)),
            ],
        ),
    ]
