# Generated by Django 4.1.5 on 2023-01-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nascimento', models.DateTimeField()),
                ('senha', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
